### ISSUE TITLE
Customizing distance function in k-means algorithm

### ISSUE THREAD

**Issue by zeyutang** [stephenbeckr/SparsifiedKMeans#2]
Hi~
I want to use a specific distance function (not provided in Matlab's original `k-means`) due to the structure of data I am dealing with. Since the distance function can simply be written as "distance = function(point_1, point_2)", I am wondering if customized distance function can be used in your wonderful implementation of K-means algorithm. Thank you~

**Comment by stephenbeckr** [comment]
The short answer is Yes, that should work fine. But there are two issues: first, our theory is specific to the Euclidean distance, so it's not as clear if our preconditioning+sparsification will work as well in other norms (e.g., the preconditioning doesn't change Euclidean distances, but it will induce small changes in other distances). Second, there's the implementation issue, and for some of the very computation-heavy parts of the code we use a very specific Matlab routine (or we have C code we can use), so modifying this may take a little bit of work, depending on how much you want to optimize the code.
-Stephen

**Comment by zeyutang** [comment]
OK, I see. Thanks a lot!
