### ISSUE TITLE
can't run 'example_loadFromDisk.m'

### ISSUE THREAD

**Issue by SikaStar** [stephenbeckr/SparsifiedKMeans#4]
Hello, when I try to run your demo, I have come across a problem. When I run the file 'example_loadFromDisk.m', the bug shows that `Y   = [Y Yj]; ` in file sampleAndMixFromLargeFile.m that the dim of Y and Yj is not equal. Could you help me with this problem? Thanks a lot.

**Comment by stephenbeckr** [comment]
That was a bug in how we were dealing with sparse matrices. This latest commit should fix it, so please update. Thanks for letting us know!
