### ISSUE TITLE
Compile error of 'hadamard_pthreads.c'

### ISSUE THREAD

**Issue by dgliu** [stephenbeckr/SparsifiedKMeans#5]
Hey, dear stephen
When I run 'setup_kmeans', 'hadamard_pthreads.c' can't compile successfully, because “pthread.h”: No such file or directory.
Can you tell me if it is a real missing file or I can simply remove this line from code?
Best regards.

**Comment by dgliu** [comment]
My compiler is Microsoft Visual C++ 2015 (C), and Matlab's version is 2018a. Other c file are complied good.

**Comment by stephenbeckr** [comment]
With gcc or clang, we give the compiler the flag `-pthread`, and this tells the compiler to look in standard locations for pthread.h. With Windows and MVC, you'd need to figure out what the appropriate flag is (and make sure you have the pthread library installed, if it's not already there by default).

But overall, I would say that don't worry about it: just ignore the error. This "hadamard_pthreads.c" is just a faster version of the hadamard code, and the code will run fine with the standard version. You can also run the code using the dct to mix as well.

If the main code doesn't run, let me know and I can try to help.
